import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

//export default sidebars;

export default {
  tutorialSidebar: [
    'SwamiSaranam/kannimoola_ganapathi',//1
    'SwamiSaranam/bagavaan_saranam_bagavathi_saranam',//2
    'SwamiSaranam/thalladi_thalladi',//3
    'SwamiSaranam/poy_inri_meyyodu_nai_kondu_ponaal',//4
    'SwamiSaranam/pallikkattu_sabari_malaikku',//5
    'SwamiSaranam/vanpuli_mel_eerivarum_engal_veeramani_kandane_va',//6
    'SwamiSaranam/om_guru_naadha_ayyappa',//7
    'SwamiSaranam/anjumalai_azhaga_ayyya',//8
    'SwamiSaranam/villali_veeran_ayya',//9
    'SwamiSaranam/antha_vaaraa_ayya',//10
    'SwamiSaranam/odiva_ayya_odaivaa_samy',//11
    'SwamiSaranam/annadaan_prabhuve_saranam_ayyappa',//12
    'SwamiSaranam/odivaa_ayya_odaivaa',//13
    'SwamiSaranam/vaa_anga_vaa_sabari_malayakku_vaa',//14
    'SwamiSaranam/engae_manakudhu',//15
    'SwamiSaranam/harivarasanam',//16
    'SwamiSaranam/malaiya_maliazhaga',//17
    'SwamiSaranam/kannalae_parumaiya',//18
    'SwamiSaranam/sannadhiyil_kattamkatti',//19
    'SwamiSaranam/Samy_Samy_iyappa',//20
    'SwamiSaranam/ethana_piravigal_eduthalum',//21
    'SwamiSaranam/ganesha_charanam',//22
    'SwamiSaranam/alaikatuma_samy_alaikatuma',//23
    'SwamiSaranam/athisesha',//24
    'SwamiSaranam/vatta_nalla_pottu_vachu',//25
    'SwamiSaranam/ennalum_unnamam',//26
    'SwamiSaranam/indha_kana_karunkuzhil',//27
    'SwamiSaranam/samayapura_mariyamma',//28
    'SwamiSaranam/gurusamy',//29
    'SwamiSaranam/bala_bala',//30
    'SwamiSaranam/kattu_vali',//31
    'SwamiSaranam/ana_puli',//32
    'SwamiSaranam/kattoda_kattumudi',//33
    'SwamiSaranam/villali_veeranaee',//34
    'SwamiSaranam/sannadhiyil_kattumkatti_vandhomappa_iyappa',//35
    'SwamiSaranam/samiyappa_samiyappa',//36
    'SwamiSaranam/alaga',//37
    'SwamiSaranam/pon_unjal',//38
    'SwamiSaranam/Sabarimalavasa_Gana',//39
    'SwamiSaranam/Vanpuli',//40
    'SwamiSaranam/alilladha_kattukulla',//41
    'SwamiSaranam/nee_indri_valveadhu',//42
    'SwamiSaranam/jaiganesha_jaiganesha',//43
    'SwamiSaranam/odakarai_mannueduthu',//44
    'SwamiSaranam/chinna_pullai',//45
    'SwamiSaranam/unnai_devaim_enbadha',//46
    'SwamiSaranam/adi_varugudhu',//47
    'SwamiSaranam/odi_vaa_muruga',//48
    'SwamiSaranam/vararaya_vararu',//49


  ],
  tutorialSidebar1: [
    'Karupasamy/karupu_uoruvam_pondavaram',
    'Karupasamy/enga_karupasamy',
    'Karupasamy/anga_idi_mulangudhu',
    'Karupasamy/karupan_alaipu'
  ]
};
